import numpy as np
import tensorflow as tf

LEARNING_RATE = 1e-4
MLP_LAYERS_PARAMS = (256, 256, 32, 16)

STARTING_EPSILON = 0.8
ENDING_EPSILON = 0.3
EXPLORE_STEPS = 10_000
DISCOUNT_FACTOR = 0.8

REPLAY_BUFFER_CAPACITY = 1_000_000

# For replay buffer
# Number of timestep each sample consist of.
# Most performant when equal to `num_steps` passed to `as_dataset`.
REPLAY_BUFFER_SEQUENCE_LENGTH = 2 #default was 2.

NUMBER_OF_EVAL_EPISODES = 3

COLLECT_STEPS_PER_ITERATION = 1_000
COLLECT_EPISODES_PER_ITERATION = 10
NUMBER_OF_ITERATIONS = 10_000

BATCH_SIZE = 256
NUMBER_OF_PARALLEL_CALL = 16
PREFETCH_NUMBER_OF_BATCH = 16

LOG_INTERVAL = 20
EVAL_ITEATION_INTERVAL = 100

LEVEL_UP_RETURN_THRESHOLD = 0.5